import { useEffect } from 'react';
import './infoPage.css';

function InfoPage() {
  useEffect(() => {
    const boxes = document.querySelectorAll('.box');

    function checkBoxes() {
      const triggerBottom = (window.innerHeight / 5) * 4;

      boxes.forEach((box) => {
        const boxTop = box.getBoundingClientRect().top;

        if (boxTop < triggerBottom) {
          box.classList.add('show');
        } else {
          box.classList.remove('show');
        }
      });
    }

    window.addEventListener('scroll', checkBoxes);
    checkBoxes();

    return () => {
      window.removeEventListener('scroll', checkBoxes);
    };
  }, []);

  return (
    <div className="md:container md:mx-auto mt-4 md:mt-4 lg:mt-8 ">
      <div className="box">
        <h2 className="text-4xl">Solar Panels</h2>
        <p className="pt-6 text-base">
          Solar panels, also known as photovoltaic (PV) panels, are devices that
          convert sunlight into electricity. They are made up of multiple solar
          cells, which are typically made from silicon-based materials. When
          sunlight hits these cells, it excites electrons, creating a flow of
          electricity. This electricity can then be used to power various
          devices or stored in batteries for later use. The most common type of
          solar panel is made from crystalline silicon, either monocrystalline
          or polycrystalline. Thin-film solar panels are another type, made from
          materials like cadmium telluride or amorphous silicon.
        </p>
      </div>
      <div className="box">
        <h2 className="text-4xl">How Do Solar Panels Work?</h2>
        <p className="pt-6 text-base">
          Solar panels work by harnessing the energy from sunlight and
          converting it into electricity through a process called the
          photovoltaic effect. Here is a simplified explanation of how this
          process works: Absorption of sunlight: Solar panels are made up of
          numerous solar cells, typically made from silicon-based materials.
          These cells have two layers: a positively charged layer and a
          negatively charged layer. When sunlight hits the solar panel, it is
          absorbed by the silicon material. Generation of electric current: When
          sunlight is absorbed by the silicon material, it excites the electrons
          in the material, causing them to move. This movement of electrons
          creates an electric current. The electric current generated by each
          solar cell is direct current (DC). Conversion to usable electricity:
          The direct current (DC) electricity generated by the solar cells needs
          to be converted into alternating current (AC) electricity, which is
          what most homes and businesses use. This conversion is done by a
          device called an inverter, which is typically installed alongside the
          solar panels. Utilization or storage of electricity: The AC
          electricity produced by the solar panels can now be used to power
          electrical devices, appliances, lighting, and other electrical loads
          in a home or business. Any excess electricity generated by the solar
          panels can be stored in batteries for later use or exported to the
          grid, depending on the setup.
        </p>
      </div>
      <div className="box">
        <h2 className="text-4xl">Causes of Deterioration of Solar Panels</h2>
        <p className="pt-6 text-base">
          The deterioration of solar panels can occur due to various factors,
          including: Exposure to environmental elements: Solar panels are
          exposed to harsh environmental conditions such as sunlight, rain,
          wind, hail, snow, and temperature fluctuations. Over time, prolonged
          exposure to these elements can lead to degradation of the panel
          materials, including the glass, frame, and encapsulant. UV radiation:
          Solar panels are exposed to ultraviolet (UV) radiation from sunlight,
          which can cause degradation of the materials used in the solar cells
          and the encapsulant. This can result in a decrease in the efficiency
          of the solar panels over time. Dust and dirt accumulation: Dust, dirt,
          and other particles can accumulate on the surface of solar panels,
          reducing the amount of sunlight that reaches the solar cells and
          decreasing the efficiency of the panels. Regular cleaning is necessary
          to maintain optimal performance. Mechanical stress: Mechanical stress
          from factors such as wind, hail, or improper installation can damage
          the solar panels or their components, leading to reduced efficiency or
          failure. Temperature variations: Solar panels are designed to operate
          within a certain temperature range, and extreme temperatures can
          affect their performance. High temperatures can cause thermal
          degradation of the materials, while rapid temperature changes can lead
          to mechanical stress and potential damage. Humidity and moisture:
          Moisture ingress into the solar panel components can cause corrosion,
          delamination, or electrical insulation failure, leading to reduced
          performance or malfunction. Manufacturing defects: Defects in the
          manufacturing process, such as material impurities, soldering issues,
          or improper encapsulation, can lead to premature degradation or
          failure of the solar panels. Age: Like any electronic device, solar
          panels degrade over time due to wear and tear. This degradation can
          result in a decrease in efficiency and output power over the lifespan
          of the panels.
        </p>
      </div>
      <div className="box">
        <h2 className="text-4xl">Advantages of Solar Panels</h2>
        <p className="pt-6 text-base">
          Solar panels offer numerous advantages, making them a popular choice
          for renewable energy generation. Here are some key advantages: Clean
          and Renewable Energy Source: Solar panels harness sunlight, a
          virtually limitless and renewable energy source. Unlike fossil fuels,
          solar energy production does not release harmful greenhouse gases or
          pollutants, contributing to a cleaner environment and mitigating
          climate change. Reduced Electricity Bills: By generating electricity
          from sunlight, solar panels can significantly reduce or even eliminate
          dependence on traditional grid-supplied electricity. This can lead to
          substantial savings on electricity bills over the lifespan of the
          solar panel system, especially in areas with high electricity rates or
          ample sunlight.Low Operating Costs: Once installed, solar panels have
          minimal operating and maintenance costs. They require occasional
          cleaning and inspection to ensure optimal performance but do not incur
          fuel costs or ongoing expenses associated with traditional energy
          sources. Long-Term Investment: Solar panel systems typically have long
          lifespans, often exceeding 25 years or more with proper maintenance.
          As the cost of solar technology continues to decline and energy prices
          rise, investing in solar panels can yield substantial returns over
          their lifespan, providing a reliable source of electricity and
          potential financial savings. Scalability and Flexibility: Solar panel
          systems can be tailored to meet diverse energy needs, ranging from
          small residential installations to large-scale utility projects. They
          can be easily expanded or integrated with existing infrastructure,
          offering flexibility and scalability to accommodate changing energy
          demands. Environmental Benefits: Solar energy production helps reduce
          air and water pollution, conserve natural resources, and protect
          ecosystems. By displacing fossil fuel consumption, solar panels
          mitigate the environmental impacts associated with extraction,
          transportation, and combustion of conventional energy sources.
        </p>
      </div>
      <div className="box">
        <h2 className="text-4xl">Solar Panel Applications</h2>
        <p className="pt-6 text-base">
          Solar panels have diverse applications across various sectors,
          harnessing sunlight to generate electricity and provide sustainable
          energy solutions. Here are some common applications: Residential Solar
          Systems: Solar panels are widely used on residential rooftops to
          generate electricity for homes. These systems can offset electricity
          bills, increase energy independence, and reduce carbon footprints.
          Residential solar installations often include grid-tied systems,
          off-grid systems with battery storage, or hybrid systems that combine
          solar with other energy sources. Utility-Scale Solar Farms:
          Large-scale solar farms or solar power plants deploy extensive arrays
          of solar panels to generate electricity for utility grids. These
          utility-scale installations contribute to the expansion of renewable
          energy capacity, enhance grid reliability, and support decarbonization
          efforts. Solar farms can be ground-mounted or installed on unused
          land, providing a reliable and scalable energy source. Off-Grid Power
          Systems: Solar panels are utilized in off-grid applications where
          access to traditional grid electricity is limited or unavailable.
          Off-grid solar systems, often combined with battery storage and backup
          generators, provide reliable power for remote homes, cabins,
          recreational vehicles (RVs), telecommunications towers, and off-grid
          communities. These systems offer energy independence and resilience in
          remote locations. Solar-Powered Vehicles and Transportation: Solar
          panels are integrated into vehicles, including cars, boats, drones,
          and satellites, to supplement onboard power systems and extend range
          or endurance. Solar-powered transportation solutions harness sunlight
          to charge batteries, reduce fuel consumption, and lower carbon
          emissions, contributing to sustainable mobility and transportation
          innovation.
        </p>
      </div>
      <div className="box">
        <h2 className="text-4xl">The Future of Solar Panels</h2>
        <p className="pt-6 text-base">
          The future of solar panels holds promise for further advancements in
          technology, efficiency, and integration, driving increased adoption
          and broader applications. Here are some key trends and developments
          shaping the future of solar panels: Increased Efficiency: Research and
          development efforts continue to enhance the efficiency of solar
          panels, improving their ability to convert sunlight into electricity.
          Innovations in materials, manufacturing processes, and cell designs
          aim to boost efficiency levels, maximizing energy output while
          reducing the overall cost per watt. Advanced Photovoltaic
          Technologies: Emerging photovoltaic technologies, such as perovskite
          solar cells, tandem solar cells, and thin-film solar technologies,
          show potential for higher efficiency and lower manufacturing costs
          compared to traditional silicon-based solar cells. These
          next-generation technologies offer improved performance in low-light
          conditions, flexibility, and scalability, expanding the range of solar
          panel applications. Energy Storage Integration: The integration of
          energy storage solutions, such as lithium-ion batteries, with solar
          panel systems enhances grid stability, enables energy
          self-consumption, and facilitates grid independence. Advances in
          battery technology, coupled with declining costs, make
          solar-plus-storage systems increasingly viable for residential,
          commercial, and utility-scale applications, providing reliable and
          dispatchable renewable energy.
        </p>
      </div>
    </div>
  );
}

export default InfoPage;
