import 'primereact/resources/themes/bootstrap4-dark-blue/theme.css';
import 'primeicons/primeicons.css';

import './infoPage.css';
import { LineChart } from '@mui/x-charts/LineChart';

export default function InfoPage() {
  return (
    <div>
      <div>
        <div id="section1" className="box">
          <p className="pt-2 pb-6 text-lg">
            <strong>Solar panels</strong> , also known as photovoltaic (PV)
            panels, are devices that convert sunlight into electricity. They are
            made up of multiple solar cells, which are typically made from
            silicon-based materials. When sunlight hits these cells, it excites
            electrons, creating a flow of electricity. This electricity can then
            be used to power various devices or stored in batteries for later
            use. The most common type of solar panel is made from crystalline
            silicon, either monocrystalline or polycrystalline. Thin-film solar
            panels are another type, made from materials like cadmium telluride
            or amorphous silicon.
          </p>
          <div
            className="content-wrapper"
            style={{ display: 'flex', justifyContent: 'center' }}
          >
            <img
              src="https://premierenergysolutionja.com/wp-content/uploads/2023/06/How-Does-Solar-Power-Work-For-Your-Home.jpeg"
              alt="solar panel"
              className="image-wrapper"
              style={{ maxWidth: '100%', width: '600px' }}
            />
          </div>
        </div>

        <div id="section2" className="box ">
          <h2 className="text-4xl font-bold ">How Do Solar Panels Work?</h2>
          <p className="pt-6 text-lg">
            Solar panels work by harnessing the energy from sunlight and
            converting it into electricity through a process called the
            photovoltaic effect. Here is a simplified explanation of how this
            process works:
          </p>
          <p className="pt-4 text-lg">
            <strong>Absorption of sunlight: </strong>Solar panels are made up of
            numerous solar cells, typically made from silicon-based materials.
            These cells have two layers: a positively charged layer and a
            negatively charged layer. When sunlight hits the solar panel, it is
            absorbed by the silicon material.
          </p>
          <p className="pt-4 text-lg">
            <strong>Generation of electric current:</strong> When sunlight is
            absorbed by the silicon material, it excites the electrons in the
            material, causing them to move. This movement of electrons creates
            an electric current. The electric current generated by each solar
            cell is direct current (DC). Conversion to usable electricity: The
            direct current (DC) electricity generated by the solar cells needs
            to be converted into alternating current (AC) electricity, which is
            what most homes and businesses use. This conversion is done by a
            device called an inverter, which is typically installed alongside
            the solar panels.
          </p>
          <p className="pt-4 text-lg">
            <strong>Utilization or storage of electricity:</strong> The AC
            electricity produced by the solar panels can now be used to power
            electrical devices, appliances, lighting, and other electrical loads
            in a home or business. Any excess electricity generated by the solar
            panels can be stored in batteries for later use or exported to the
            grid, depending on the setup.
          </p>
        </div>

        <div id="section3" className="box">
          <h2 className="text-4xl font-bold">Solar panel installation</h2>
          <p className="pt-6 text-lg">
            Most residential solar arrays are installed by a professional.
            Installing solar panels yourself is technically possible, but you
            run the risk of voiding warranties. You should only attempt it if
            you have the necessary expertise. If you opt for a professional
            installation, be sure to shop around for the best deal. Compare the
            warranties installers offer along with price, customer service and
            how well their proposed plans meet your needs.
          </p>
          <div
            className="mt-8 mb-8 content-wrapper"
            style={{ display: 'flex', justifyContent: 'center' }}
          >
            <img
              src="https://media.licdn.com/dms/image/D4D12AQEw2Qbzs-Z5Xw/article-cover_image-shrink_720_1280/0/1684391933014?e=2147483647&v=beta&t=MlQdHX50E226Q6qpUawtxntIxBxPavrKgGBUdkq5mpU"
              alt="solar panel installation"
              className="image-wrapper"
              style={{ maxWidth: '100%' }}
            />
          </div>
          <p className="pt-4 text-lg">
            A reputable solar installer will advise you on the age of your roof
            before installation. Replacing your roof before installation may
            ultimately be the cheaper option, since removing the panels to
            replace the roof will be an additional expense.
          </p>
        </div>

        <div id="section4" className="box">
          <h2 className="text-4xl font-bold">
            Care and lifespan of solar panels
          </h2>
          <p className="pt-6 text-lg">
            Many solar panels are warrantied to last 25 years, though their
            useful life is likely longer. On top of that, they are fairly
            maintenance-free, just requiring that you keep them free of
            obstructions like dirt, leaves and snow. More extensive repairs may
            be covered by warranty.
          </p>
          <p className="pt-4 text-lg">
            Solar panels become less efficient over time, though that downward
            trend is not necessarily a problem for you. A typical manufacturer
            has warranty will guarantee that your solar panels will not lose
            more than 2% efficiency in the first year and not more than 0.5% per
            year in the next 24 years. That means your panels are guaranteed to
            produce at 84% their original capacity after year 25. Some panels
            will set a higher benchmark -- like 92% -- after 25 years, but you
            will still be getting plenty of electricity out of them two decades
            on.
          </p>
        </div>

        <div id="section5" className="box">
          <h2 className="text-4xl font-bold">
            Causes of Deterioration of Solar Panels
          </h2>
          <p className="pt-6 text-lg">
            The deterioration of solar panels can occur due to various factors,
            including:
          </p>
          <p className="pt-4 text-lg">
            <strong>Exposure to environmental elements:</strong> Solar panels
            are exposed to harsh environmental conditions such as sunlight,
            rain, wind, hail, snow, and temperature fluctuations. Over time,
            prolonged exposure to these elements can lead to degradation of the
            panel materials, including the glass, frame, and encapsulant.
          </p>
          <p className="pt-4 text-lg">
            <strong> UV radiation:</strong> Solar panels are exposed to
            ultraviolet (UV) radiation from sunlight, which can cause
            degradation of the materials used in the solar cells and the
            encapsulant. This can result in a decrease in the efficiency of the
            solar panels over time.
          </p>
          <p className="pt-4 text-lg">
            <strong>Dust and dirt accumulation: </strong> Dust, dirt, and other
            particles can accumulate on the surface of solar panels, reducing
            the amount of sunlight that reaches the solar cells and decreasing
            the efficiency of the panels. Regular cleaning is necessary to
            maintain optimal performance.
          </p>
          <p className="pt-4 text-lg">
            <strong> Mechanical stress:</strong> Mechanical stress from factors
            such as wind, hail, or improper installation can damage the solar
            panels or their components, leading to reduced efficiency or
            failure.
          </p>
          <p className="pt-4 text-lg">
            <strong>Temperature variations:</strong> Solar panels are designed
            to operate within a certain temperature range, and extreme
            temperatures can affect their performance. High temperatures can
            cause thermal degradation of the materials, while rapid temperature
            changes can lead to mechanical stress and potential damage.
          </p>
          <div className="pt-8">
            <LineChart
              xAxis={[
                {
                  data: [
                    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                    18, 19, 20, 21, 22, 23, 24, 25,
                  ],
                },
              ]}
              series={[
                {
                  data: [
                    99, 98, 97.5, 97, 96.5, 96, 95.5, 95, 94.5, 94, 93.5, 93,
                    92, 91, 90.5, 90, 89, 88.5, 88, 87, 86, 85, 84, 83, 82,
                  ],
                },
              ]}
              height={300}
              margin={{ left: 30, right: 30, top: 30, bottom: 30 }}
              grid={{ vertical: true, horizontal: true }}
            />
            <h2 className="text-black font-medium">
              Solar Panel Efficiency Degradation After Time(years)
            </h2>
          </div>
        </div>

        <div id="section6" className="box">
          <h2 className="text-4xl font-bold">Advantages of Solar Panels</h2>
          <p className="pt-6 text-lg">
            Solar panels offer numerous advantages, making them a popular choice
            for renewable energy generation. Here are some key advantages:
          </p>
          <p className="pt-4 text-lg">
            <strong>Clean and Renewable Energy Source:</strong> Solar panels
            harness sunlight, a virtually limitless and renewable energy source.
            Unlike fossil fuels, solar energy production does not release
            harmful greenhouse gases or pollutants, contributing to a cleaner
            environment and mitigating climate change.
          </p>
          <p className="pt-4 text-lg">
            <strong>Reduced Electricity Bills:</strong> By generating
            electricity from sunlight, solar panels can significantly reduce or
            even eliminate dependence on traditional grid-supplied electricity.
            This can lead to substantial savings on electricity bills over the
            lifespan of the solar panel system, especially in areas with high
            electricity rates or ample sunlight.
          </p>
          <p className="pt-4 text-lg">
            <strong>Low Operating Costs:</strong> Once installed, solar panels
            have minimal operating and maintenance costs. They require
            occasional cleaning and inspection to ensure optimal performance but
            do not incur fuel costs or ongoing expenses associated with
            traditional energy sources.
          </p>
          <p className="pt-4 text-lg">
            <strong>Scalability and Flexibility:</strong> Solar panel systems
            can be tailored to meet diverse energy needs, ranging from small
            residential installations to large-scale utility projects. They can
            be easily expanded or integrated with existing infrastructure,
            offering flexibility and scalability to accommodate changing energy
            demands.
          </p>
          <p className="pt-4 text-lg">
            <strong>Environmental Benefits: </strong>Solar energy production
            helps reduce air and water pollution, conserve natural resources,
            and protect ecosystems. By displacing fossil fuel consumption, solar
            panels mitigate the environmental impacts associated with
            extraction, transportation, and combustion of conventional energy
            sources.
          </p>
        </div>

        <div id="section7" className="box ">
          <h2 className="text-4xl font-bold ">Solar Panel Applications</h2>
          <p className="pt-6 text-lg">
            Solar panels have diverse applications across various sectors,
            harnessing sunlight to generate electricity and provide sustainable
            energy solutions. Here are some common applications:
          </p>
          <p className="pt-4 text-lg">
            <strong>Residential Solar Systems:</strong> Solar panels are widely
            used on residential rooftops to generate electricity for homes.
            These systems can offset electricity bills, increase energy
            independence, and reduce carbon footprints. Residential solar
            installations often include grid-tied systems, off-grid systems with
            battery storage, or hybrid systems that combine solar with other
            energy sources.
          </p>
          <p className="pt-4 text-lg">
            <strong>Utility-Scale Solar Farms:</strong> Large-scale solar farms
            or solar power plants deploy extensive arrays of solar panels to
            generate electricity for utility grids. These utility-scale
            installations contribute to the expansion of renewable energy
            capacity, enhance grid reliability, and support decarbonization
            efforts. Solar farms can be ground-mounted or installed on unused
            land, providing a reliable and scalable energy source.
          </p>
          <p className="pt-4 text-lg">
            <strong>Off-Grid Power Systems: </strong>Solar panels are utilized
            in off-grid applications where access to traditional grid
            electricity is limited or unavailable. Off-grid solar systems, often
            combined with battery storage and backup generators, provide
            reliable power for remote homes, cabins, recreational vehicles
            (RVs), telecommunications towers, and off-grid communities. These
            systems offer energy independence and resilience in remote
            locations.
          </p>
          <p className="pt-4 text-lg">
            <strong>Solar-Powered Vehicles and Transportation:</strong> Solar
            panels are integrated into vehicles, including cars, boats, drones,
            and satellites, to supplement onboard power systems and extend range
            or endurance. Solar-powered transportation solutions harness
            sunlight to charge batteries, reduce fuel consumption, and lower
            carbon emissions, contributing to sustainable mobility and
            transportation innovation.
          </p>
          <div className="mt-8 flex justify-center">
            <img
              src="https://ae01.alicdn.com/kf/Had18a6405212459ba2c9b030756cb230v/100W-Foldable-Solar-Panel-Dual-USB-Solar-System-Solar-Panel-Waterproof-Kit-Complete-RV-Car-Battery.jpg"
              alt="solar panel widely used"
              className="image-wrapper"
              style={{ maxWidth: '50%', mixBlendMode: 'darken' }}
            />
          </div>
        </div>

        <div id="section8" className="box">
          <h2 className="text-4xl font-bold">The Future of Solar Panels</h2>
          <p className="pt-6 text-lg">
            The future of solar panels holds promise for further advancements in
            technology, efficiency, and integration, driving increased adoption
            and broader applications. Here are some key trends and developments
            shaping the future of solar panels:
          </p>
          <p className="pt-4 text-lg">
            <strong>Increased Efficiency:</strong> Research and development
            efforts continue to enhance the efficiency of solar panels,
            improving their ability to convert sunlight into electricity.
            Innovations in materials, manufacturing processes, and cell designs
            aim to boost efficiency levels, maximizing energy output while
            reducing the overall cost per watt.
          </p>
          <p className="pt-4 text-lg">
            <strong> Advanced Photovoltaic Technologies:</strong> Emerging
            photovoltaic technologies, such as perovskite solar cells, tandem
            solar cells, and thin-film solar technologies, show potential for
            higher efficiency and lower manufacturing costs compared to
            traditional silicon-based solar cells. These next-generation
            technologies offer improved performance in low-light conditions,
            flexibility, and scalability, expanding the range of solar panel
            applications.
          </p>
          <p className="pt-4 text-lg">
            <strong>Energy Storage Integration:</strong> The integration of
            energy storage solutions, such as lithium-ion batteries, with solar
            panel systems enhances grid stability, enables energy
            self-consumption, and facilitates grid independence. Advances in
            battery technology, coupled with declining costs, make
            solar-plus-storage systems increasingly viable for residential,
            commercial, and utility-scale applications, providing reliable and
            dispatchable renewable energy.
          </p>
          <div className="mt-8 content-wrapper flex justify-center">
            <img
              src="https://greenhomesystems.com/wp-content/uploads/2023/09/blog-cover-photo-98.jpg"
              alt="solar panel 2"
              className="image-wrapper"
              style={{ maxWidth: '60%' }}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
